  - platform: uptime
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: ring
  - platform: speedtest
    minute: 30
    hour:
      - 0
      - 12
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: bitcoin
    display_options:
      - exchangerate
  - platform: yr
  - platform: dnsip
    name: "MyIP"
  - platform: mqtt
    state_topic: "ha/wine/Humidity"
    name: "Wine Room Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value }}'
  - platform: rest
    resource: https://api.enphaseenergy.com/api/v2/systems/585444/summary?key=b99f94ecb36851197a00d112579d9769&user_id=4e6a4d7a4e4459340a
    value_template: '{{ value_json.current_power }}'
    scan_interval: 300
    name: "Current Solar Power"
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: processor_use
      - type: since_last_boot
  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n
  - platform: template
    sensors:
      entrancemd_tripped:
        value_template: '{{ ((as_timestamp(now())-as_timestamp(states.binary_sensor.entrance_motion.last_changed))/60) | round (0)}}'
      familymd_tripped:
        value_template: '{{ ((as_timestamp(now())-as_timestamp(states.binary_sensor.family_motion.last_changed))/60) | round (0)}}'
      basementmd_tripped:
        value_template: '{{ ((as_timestamp(now())-as_timestamp(states.binary_sensor.basement_motion.last_changed))/60) | round (0)}}'
      frontdoor_tripped:
        value_template: '{{ ((as_timestamp(now())-as_timestamp(states.binary_sensor.front_door.last_changed))/60) | round (0)}}'
      last_motion:
        friendly_name: 'Last Motion'
        value_template: >
          {%- set sensors = [states("sensor.basementmd_tripped") | int, states("sensor.entrancemd_tripped") | int, states("sensor.familymd_tripped") | int , states("sensor.frontdoor_tripped")| int] -%}
          {{ sensors | min }}
      wine_iscooling:
        value_template: '{% if is_state("climate.wine_room_temp", "Cooling") -%}1{%- else -%}0{%- endif %}'
      wine_cooling_since:
        entity_id: sensor.time
        value_template: '{% if is_state("sensor.wine_iscooling", "1")  -%}{{ ((as_timestamp(now())-as_timestamp(states.sensor.wine_iscooling.last_updated))/60) | round (0)}}{%- else -%}0{%- endif %}'
      wine_isdefrosting:
        value_template: '{% if is_state("climate.fin_temps", "Defrosting") -%}1{%- else -%}0{%- endif %}'
      zwave_front_door_battery:
        value_template: '{{ states.zwave.schlage_be469nxcen_touchscreen_deadbolt.attributes.battery_level|default(0) }}'
        icon_template: >
          {% set battery_level = states.zwave.schlage_be469nxcen_touchscreen_deadbolt.attributes.battery_level | default(0) | int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
